### ISSUE TITLE
Document how to change extension

### ISSUE THREAD

**Issue by dustingetz** [TannerRogalsky/sprockets-es6#12]
I want to configure this to run *.js through babel, can we document how to do this pls? thanks

**Comment by TannerRogalsky** [comment]
There are a number of possible solutions. You might register this gem as a transformer for the javascript mime type. You might register a self-written postprocessor for javascript that does this transformation. 

Neither of these solutions are typical of the sprockets pipeline which encourages modifying extensions for transformers. Applying the `.es6` extension will continue to be the documented way to use this gem.

**Comment by Valve** [comment]
@TannerRogalsky what about .jsx files? Is it possible to process .jsx files (which have a mixture of JSX and ES6 in them)?

**Comment by TannerRogalsky** [comment]
@Valve For the case of .jsx files, I would probably recommend you registering them to be compiled by this gem. Should be simple enough because of the unique extension. See the relevant code here: https://github.com/TannerRogalsky/sprockets-es6/blob/aa733e95a97715946647381869bd4dbc856e1a2c/lib/sprockets/es6.rb#L50-L52

**Comment by Valve** [comment]
do you want me to do a PR for this?

**Comment by Valve** [comment]
https://github.com/TannerRogalsky/sprockets-es6/pull/14 should fix it
